server:
  port: 8080

spring:
  application:
    name: LiteratureForum-Backend

  mail:
    host: smtp.gmail.com
    port: 587
    username: tuanpham.5417@gmail.com
    password: ymmo igpw qell gzif
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/literature_forum
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: LiteratureForum-HikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000 # 30s
      max-lifetime: 1800000 # 30 phút

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  jackson:
    default-property-inclusion: non_null
#    serialization:
#      write-dates-as-timestamps: false

application:
  mail:
    username: tuanpham.5417@gmail.com
  api:
    prefix: /api/v1
    base-url: http://localhost:5432
  security:
    google:
      client-id: 14211856446-caghped7p93fpf488vabutgjpeitjl7o.apps.googleusercontent.com
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000 # 1 ngày (ms)
      refresh-token:
        expiration: 604800000
