spring:
  # 1. Database H2 (Giữ nguyên)
  datasource:
    url: jdbc:h2:mem:literatureforum_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # 2. JPA (Giữ nguyên)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # 3. Flyway (Giữ nguyên - Tắt đi)
  flyway:
    enabled: false

  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

application:
  mail:
    username: tuanpham.5417@gmail.com
  api:
    prefix: /api/v1
    base-url: http://localhost:5432
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000 # 1 ngày (ms)
      refresh-token:
        expiration: 604800000
